/* eslint-disable @next/next/no-img-element */
import QRCode from "qrcode";
import Link from "next/link";

type Props = {
  params: { text: string };
};

export async function genMetadata({ params }: Props) {

  const ogImageUrl = `${process.env.VERCEL_URL || 'http:localhost:3000'}/api/og?text=${params.text}`;

  return {
    title: 'QRCode',
    description: 'Generated by My app',
    openGraph: {
      title: 'Hello World',
      description: 'Scan this image to see the content.',
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: 'QR Code Preview',
        },
      ],
    },
  };
}

export default async function SharePage({ params }: Props) {
  const decodedText = Buffer.from(params.text, 'base64').toString('utf8');
  const qrDataUrl = await QRCode.toDataURL(decodedText, { width: 300 });

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 p-4">
      <div className="bg-white p-8 rounded-xl shadow-lg flex flex-col items-center max-w-md w-full">
        <h1 className="text-2xl font-bold mb-6 text-gray-800">QR Code Shared</h1>

        <img src={qrDataUrl} alt="QR Code" className="mb-6 border rounded-lg" />

        <div className="bg-gray-100 p-4 rounded-lg w-full mb-6 wrap-break-word">
          <p className="text-sm text-gray-500 mb-1">Nội dung:</p>
          <p className="font-mono text-gray-800">{decodedText}</p>
        </div>

        <Link
          href="/"
          className="bg-blue-600 text-white px-6 py-2 rounded-full hover:bg-blue-700 transition"
        >
          Tạo QR mới
        </Link>
      </div>
    </div>
  );
}