/* eslint-disable @next/next/no-img-element */
import QRCode from "qrcode";
import Link from "next/link";
import { ViewTracker } from "@/components/ViewTracker";
import { doc, getDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";

type Props = {
  params: Promise<{ text: string }>;
  searchParams: Promise<{ id?: string }>;
};

export async function generateMetadata(props: Props) {
  const params = await props.params;
  const domain = 'https://qrcode-smart.vercel.app'; // Ideally env var
  const ogImageUrl = `${domain}/api/og?text=${params.text}&title=Scan%20Me`;

  return {
    title: 'Shared QR Code | QRCode Smart',
    description: 'Scan this QR code to view the content. Generated by QRCode Smart.',
    openGraph: {
      title: 'Shared QR Code | QRCode Smart',
      description: 'Scan this QR code to view the content.',
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: 'QR Code Preview',
        },
      ],
    },
  };
}

export default async function SharePage(props: Props) {
  const params = await props.params;
  const searchParams = await props.searchParams;
  const textParam = params.text;

  let content = '';
  let qrId = searchParams.id; // Keep backward compatibility for ?id=
  let qrOptions = { dark: '#000000', light: '#ffffff' };

  // 1. Try to fetch from Firestore (assuming textParam is an ID)
  try {
    const docRef = doc(db, "qrcodes", textParam);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      content = data.content;
      qrId = docSnap.id; // Found ID from path
      if (data.qrOptions) {
        qrOptions = data.qrOptions;
      }
    }
  } catch (e) {
    // Ignore error, might not be an ID or permission issue
    console.log("Not a valid ID or DB error", e);
  }

  // 2. If not found in DB, try Base64 decode
  if (!content) {
    try {
      content = Buffer.from(textParam, 'base64').toString('utf-8');
    } catch (e) {
      console.log("Not a valid base64", e);
    }
  }

  if (!content) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-neutral-50 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100 font-sans p-4">
        <div className="text-center">
          <h1 className="text-4xl font-bold mb-4">404</h1>
          <p className="text-lg text-neutral-500 mb-8">QR Code not found or expired.</p>
          <Link href="/" className="px-6 py-3 bg-indigo-600 text-white rounded-xl font-medium">Go Home</Link>
        </div>
      </div>
    );
  }

  // Generate high-res QR for display
  const qrDataUrl = await QRCode.toDataURL(content, {
    width: 600,
    margin: 2,
    color: qrOptions
  });

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-neutral-50 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-100 font-sans p-4">
      {qrId && <ViewTracker qrId={qrId} />}

      <div className="w-full max-w-md animate-in fade-in zoom-in duration-500">
        <div className="bg-white dark:bg-neutral-900 p-8 rounded-3xl shadow-2xl border border-neutral-200 dark:border-neutral-800 flex flex-col items-center relative overflow-hidden">

          {/* Background decoration */}
          <div className="absolute top-0 left-0 w-full h-2 bg-linear-to-r from-indigo-500 via-purple-500 to-pink-500"></div>

          <div className="w-16 h-16 bg-indigo-50 dark:bg-indigo-900/20 rounded-2xl flex items-center justify-center text-indigo-600 dark:text-indigo-400 mb-6 shadow-lg shadow-indigo-500/10">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 4.875c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 013.75 9.375v-4.5zM3.75 14.625c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5a1.125 1.125 0 01-1.125-1.125v-4.5zM13.5 4.875c0-.621.504-1.125 1.125-1.125h4.5c.621 0 1.125.504 1.125 1.125v4.5c0 .621-.504 1.125-1.125 1.125h-4.5A1.125 1.125 0 0113.5 9.375v-4.5z" />
              <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 6.75h.75v.75h-.75v-.75zM6.75 16.5h.75v.75h-.75v-.75zM16.5 6.75h.75v.75h-.75v-.75zM13.5 13.5h.75v.75h-.75v-.75zM13.5 19.5h.75v.75h-.75v-.75zM19.5 13.5h.75v.75h-.75v-.75zM16.5 16.5h.75v.75h-.75v-.75z" />
            </svg>
          </div>

          <h1 className="text-2xl font-bold mb-2 text-center tracking-tight">Shared QR Code</h1>
          <p className="text-neutral-500 dark:text-neutral-400 text-center mb-8 text-sm max-w-65">
            Someone shared this content with you. Scan to view.
          </p>

          <div className="bg-white p-4 rounded-2xl shadow-inner border border-neutral-100 dark:border-neutral-800 mb-8">
            <img src={qrDataUrl} alt="QR Code" className="w-64 h-64 rounded-lg" />
          </div>

          <div className="w-full space-y-3">
            <Link
              href="/"
              className="block w-full py-3.5 bg-indigo-600 text-white rounded-xl font-semibold hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-600/20 text-center"
            >
              Create your own QR
            </Link>
          </div>
        </div>

        <div className="mt-8 text-center">
          <Link href="/" className="text-sm text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-300 transition-colors flex items-center justify-center gap-2">
            <span className="w-2 h-2 rounded-full bg-indigo-500"></span>
            Powered by QRCode Smart
          </Link>
        </div>
      </div>
    </div>
  );
}